final RegExp emailValidatorRegExp = RegExp(
    r"^[a-zA-Z0-9.a-zA-Z0-9.!#$%&'*+-/=?^_`{|}~]+@[a-zA-Z0-9]+\.[a-zA-Z]+");
final RegExp phoneValidatorRegExp = RegExp(r'(^(?:[+65])?6[0-9]{7}$)');
const String kEmailNullError = "Please enter your email!";
const String kInvalidEmailError = "Please enter Valid Email!";
const String kInvalidAddressError = "Please enter Valid Address!";
const String kPassNullError = "Please enter your password!";
const String kReTypePassNullError = "Please re-Enter your password!";
const String kShortPassError = "Password must be at least 8 characters long!";
const String kMatchPassError = "Passwords don't match!";
const String kNameNullError = "Please Enter your name!";
const String kPhoneNumberNullError = "Please enter your phone number!";
const String kInvalidPhoneNumber = "Please enter a valid phone number!";
const String kAddressNullError = "Please enter your address!";
const String kTandCAgreeError = "Please read & agree terms and conditions";
const String kPostCodeError = "Please enter valid postcode";
const String deliveryTypeNull = 'Please select a delivery type';
const String kNullInputError = 'Please Input all required fields';
const String kErrorMessage = 'Something went wrong';
const String kAppVersion = '1.0.0';
const String kDashboardPath = 'kDashboardPath';
const String kRequestPath = 'kRequestPath';
const String kUserProfilePic = 'USER_PHOTO_KEY';

const String kIslamicWillTag = "islamic-will";
const String kHealthCareDirectives = "advance-healthcare-directive";
const String kStockDonation = "stock-donate";
const generalErrorMsg = "Something went wrong";
const financialBrokerage = 'financial-brokerage';
const accountType = "account-type";
const loremIpsum =
    "Lorem Ipsum is simply dummy text of the printing and typesetting.Lorem Ipsum is simply dummy text of the printing and typesetting";
const reportKey = "reportKey";
const blockKey = "blockKey";
const authKey = "authKey";
const transferConfirmationKey = "transferConfirmationKey";
